/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */
/* Generated By:JJTree: Do not edit this line. MiniParserTreeConstants.java */

package Mini;

public interface MiniParserTreeConstants
{
  int JJTPROGRAM = 0;
  int JJTFUNDECL = 1;
  int JJTEXPR = 2;
  int JJTIFEXPR = 3;
  int JJTLETEXPR = 4;
  int JJTFUNAPPL = 5;
  int JJTTERM = 6;
  int JJTFACTOR = 7;
  int JJTVOID = 8;
  int JJTINTEGER = 9;
  int JJTIDENT = 10;


  String[] jjtNodeName = {
    "Program",
    "FunDecl",
    "Expr",
    "IfExpr",
    "LetExpr",
    "FunAppl",
    "Term",
    "Factor",
    "void",
    "Integer",
    "Ident",
  };
}
